### ISSUE TITLE
Diego - Puzzle lasers

### ISSUE THREAD

**Issue by yancouto** [MarvellousSoft/MarvInc#100]
Requirements: P4, D1, L5, J5
You have to dodge some lasers that alternate on and off every ~3 turns. (Depends on #93 )

Intro text: "Please trust me, I need help finding something out. It'll be worth it."

**Comment by yancouto** [comment]
Actually the email isn't done, only the puzzle.

**Comment by RenatoGeh** [comment]
[Email content](https://github.com/MarvellousSoft/MarvInc/blob/be1793741698d81ac650342ddc7aa964978fd847/game/emails/diego7.lua) done. Closing this issue.
