### ISSUE TITLE
Happy hour on SDD

### ISSUE THREAD

**Issue by yancouto** [MarvellousSoft/MarvInc#101]
- [x] Change party from liv6-7 to liv5-6 (@yancouto)
- [x] Jen Email: Something about work. Ends with "I'll ignore the condoms I found under my desk" (@rilifon) 
- [x] Bill Puzzle: #104 

~~Paul Email: TODO (@RenatoGeh)~~

**Comment by RenatoGeh** [comment]
Paul's HH email has been moved to Act 3.

**Comment by rilifon** [comment]
Just need to make sure all dependencies are correct, but we can check this for #108
