### ISSUE TITLE
Color all emails so far

### ISSUE THREAD

**Issue by rilifon** [MarvellousSoft/MarvInc#119]
With the new option to color emails, color all emails we have made so far

- [x] Tutorial emails

- [x] Act 1 emails

- [ ] Act 2 emails

**Comment by yancouto** [comment]
Colored all Liv emails on df8cd819fa735c0c1be2d0a7acd30e360916f2ff and d20b1a23c421fa0b097a3cf319bd30df3ef6b5f0

**Comment by RenatoGeh** [comment]
Please add a README for email coloring.

**Comment by yancouto** [comment]
The [comment o opened_email](https://github.com/MarvellousSoft/MarvInc/blob/dev/marv/classes/opened_email.lua#L14-L35) shows all available colors. Feel free to add more to the table below (they don't need to be named like colors, they can be named after what situation they should be used)

**Comment by yancouto** [comment]
The instructions are [here](https://github.com/MarvellousSoft/MarvInc/blob/dev/marv/util.lua#L246-L289) now.

**Comment by rilifon** [comment]
I colored all jen emails, plus some generic ones. I think the only emails that need coloring are Bill/Miles, Paul and Franz (if they need color at all).

I think @RenatoGeh will better complete those. If so we can close this issue \o/

**Comment by rilifon** [comment]
Needed:

- [ ] Bill/Miles
- [ ] Franz (if needed)
- [ ] Diego
