### ISSUE TITLE
Add weird sorting puzzle to the story

### ISSUE THREAD

**Issue by yancouto** [MarvellousSoft/MarvInc#125]
- [x] Create email that references it
- [x] Write its completed popup

**Comment by rilifon** [comment]
We need to find a puzzle we made that can be optimized cleverly, and if player finish that one in <x lines this puzzle will appear. Ideas?

**Comment by rilifon** [comment]
@yancouto @RenatoGeh

**Comment by yancouto** [comment]
Puzzle added, should just test if it works properly.
