### ISSUE TITLE
Last Diego email

### ISSUE THREAD

**Issue by RenatoGeh** [MarvellousSoft/MarvInc#137]
Add last Diego's email body text. Allow players to figure out this email is important. Give them some time to understand this, maybe adding a timer before emails are cleaned up.
- [x] Email body text
- [ ] Make a timer to activate the effect

**Comment by rilifon** [comment]
So I made the email body text, if you guys can please read and comment. Can someone else make the timer properly so the player can read the email for a few seconds before the screen effect and all emails be deleted?
@yancouto @RenatoGeh

**Comment by yancouto** [comment]
I added a 5-second timer. Feel free to change it.
