### ISSUE TITLE
Jen 6

### ISSUE THREAD

**Issue by RenatoGeh** [MarvellousSoft/MarvInc#146]
Email: she is pissed with you, and tells you to do what you're told and clean everything up.
Puzzle: painter blood

Puzzle extra info: PS: go fuck yourself.

**Comment by rilifon** [comment]
Is this the puzzle painter.lua, or we need to make it?

@yancouto

**Comment by yancouto** [comment]
It is. We just need to change the paint color and description.

**Comment by yancouto** [comment]
Missing (@rilifon) :

- [ ] Email
- [ ] Blood tile image
- [ ] Completed popup

**Comment by rilifon** [comment]
Describe how the blood tile should be (and if I should make variations of it)

**Comment by rilifon** [comment]
Added 4 images for blood. Can you implement them in the puzzle (and make them appear with random rotations?) @yancouto ?

**Comment by rilifon** [comment]
Added completed popup on my last commit

**Comment by rilifon** [comment]
Finished email for Jen6. Only thing left is adding the blood stains. @yancouto you'll do this?
