### ISSUE TITLE
Karl 2

### ISSUE THREAD

**Issue by RenatoGeh** [MarvellousSoft/MarvInc#147]
Email: someone is trying to hack MarvInc. He suspects it to be the FBI ("I didn't think they would go that low"). Each server node has infected another single node. He wants to find out which machine the infection first started on, and wants you to patch it.
Puzzle: stack trace

**Comment by yancouto** [comment]
Email is done but puzzle is still missing. Reopening.

**Comment by yancouto** [comment]
Just the completed popup message is missing. @RenatoGeh could you add it?
