### ISSUE TITLE
RYR

### ISSUE THREAD

**Issue by RenatoGeh** [MarvellousSoft/MarvInc#155]
Email: We send the player an email about how they've gotten rid of the middle man (Karl Franz), both because Karl bet on the wrong horse by throwing all his chips on Project Brainfuck, and because now is a critical moment in MarvInc history. We explain how we're creating a brain control system, and how this should change the world for a better, since humans are an evil, selfish, warring kind. We explain how every step we (the CEOs) take are being watched, and therefore the player should get rid of all incriminating files. And should you fulfill your duty, you will be appointed our right handman. And that the brain control project is ready for mass usage. Make the player believe he is The Chosen One.
Puzzle: 

`final puzzle`:

Four possible decisions:

1. Destroy all incriminating evidence. Show cutscene of a burning pile of evidences. (pro MarvInc)
2. Make bot (with files) throw itself out of the window. Show cutscene of it falling and papers being blown in the wind. (against MarvInc)
3. Upload files to the internet through a scanner present in the room, exposing MarvInc. Show cutscene of files being uploaded on a terminal window. (against MarvInc)
4. Make bot drop files out of the window. Show cutscene of it falling and papers being blown in the wind. (against MarvInc)

**Comment by yancouto** [comment]
Puzzle and cutscenes are done
