### ISSUE TITLE
Final newsletter

### ISSUE THREAD

**Issue by RenatoGeh** [MarvellousSoft/MarvInc#156]
Final newsletter explaining the outcomes of the player decision.

- [x] Pro MarvInc:
  * New Augmented Reality technology by MarvInc is now available, allowing you to shop, watch TV and do everything using just your thoughts.
  * MarvInc has expanded worldwide.
  * MarvInc founders are first trillionaires.
  * Smaller countries are now dependent of MarvInc.
  * New economical block has been established with all MarvInc dependent countries.
  * USA condemns MarvInc for its aggressive marketing campaign
  * USA praises MarvInc efficiency and promises future deals with MarvInc.
- [x] Against MarvInc:
  * MarvInc high management in cuffs. Many scientists being interrogated. Sources say MarvInc employee leaked confidential files.
  * Huge worldwide layoffs, as conglomerate giant MarvInc has been shutdown by the FBI.
  * MarvInc business partners go bankrupt, as they were dependent on them.
  * Homelessness rate is soaring.
  * Years after MarvInc giant fell, the world is rebuilding and things are starting to look better.
  * Future Jen: trialed and jailed.
  * Future Liv:
  * Future Paul:
- Secret ending:

**Comment by rilifon** [comment]
Added all newspapers for Pro Marv ending

**Comment by yancouto** [comment]
Added remaining newspapers for Against ending b7b9d214cab0c0a63f2b0f79df26882833b97c4d
