### ISSUE TITLE
Change paint color in Jen Puzzle 4

### ISSUE THREAD

**Issue by rilifon** [MarvellousSoft/MarvInc#160]
The paint color is black and is barely visible since it blends with the room border

**Comment by yancouto** [comment]
What color would you prefer? I can do this.

**Comment by rilifon** [comment]
Hmm try some colors and see what suits best, but anything not black or white should have good contrast enough (btw I tried to just change the color but had some troubles with it >< sorry for not doing it myself)

**Comment by yancouto** [comment]
Closed by 6947440f58242d730f1f651ddc3bf70d447f438e
