### ISSUE TITLE
Logoff Button

### ISSUE THREAD

**Issue by rilifon** [MarvellousSoft/MarvInc#162]
Button that leaves from the game screen, saves and returns to main menu screen

**Comment by yancouto** [comment]
I can implement this if there is some image for it.

**Comment by rilifon** [comment]
Suggestions for images? I can make one in Gimp today

**Comment by yancouto** [comment]
Something that looks like a power button. Or like this ![logoff](https://thumb7.shutterstock.com/display_pic_with_logo/4209790/537334795/stock-photo-logout-icon-internet-button-d-illustration-537334795.jpg)

**Comment by yancouto** [comment]
Reboot button added
