### ISSUE TITLE
Franz 1 puzzle bugs

### ISSUE THREAD

**Issue by rilifon** [MarvellousSoft/MarvInc#165]
- [ ] remove the reply button when the player finished
- [x] disable give-up button so player can't use the robot in other puzzles

**Comment by rilifon** [comment]
as discussed with @yancouto, maybe the reply button was still on the email since I was using an old save. But it's weird since even in that save I finished the puzzle again and the email still had the buttons. I will try to replicate the bug

**Comment by yancouto** [comment]
Fixed.

**Comment by rilifon** [comment]
Reply button wasn't being removed on old-saves that already had completed the puzzle, since reply button is removed only the first time the puzzle is completed.

Since this can't happen in a normal playthrough, this is a won't-fix
