### ISSUE TITLE
Puzzle List Tab

### ISSUE THREAD

**Issue by rilifon** [MarvellousSoft/MarvInc#166]
Create a Tab that should "unlock" sometime in the game (maybe after tutorial? Maybe after act 1?) that lists all puzzles the player has unlocked, separates  them in categories (most likely the persons that sent the puzzle) and marks which ones are uncompleted and completed, and which ones are the challenges emails (I think we have only 2 or 3 of those right now)

**Comment by rilifon** [comment]
This is closed i assume? Are we making it unlock in a certain act, or make it available since the beginning?

**Comment by yancouto** [comment]
After the tutorial would be best, but I'm not doing that for 1.2.2.

**Comment by rilifon** [comment]
Okay, I'll create an issue for 1.3.0. Closing this one
