### ISSUE TITLE
[Feature] Tile coords highlight on mousehover

### ISSUE THREAD

**Issue by Houkime** [MarvellousSoft/MarvInc#183]
Coords are highlighted for a bot current position, but there's no highlighting for mouse cursor coords. Would be handy to measure distances with less effort. Maybe in another color from bot's highlight.

**Comment by RenatoGeh** [comment]
This should be a quick and easy feature to implement. We might add it in the next polished version. Thanks you for the suggestion.

**Comment by RenatoGeh** [comment]
Commit 66d3a52e3e9d176d4c1ba38c662ad29c9d233f79 closes this issue.
