### ISSUE TITLE
[Bug] No codescreen scrolling possible while running/paused

### ISSUE THREAD

**Issue by Houkime** [MarvellousSoft/MarvInc#184]
Currently it is not possible to scroll code while mid-execution. Very unhandy since active row in step-by-step exec mode can just go out of  the screen and you can't see anything.

**Comment by yancouto** [comment]
Will do. Thanks

**Comment by yancouto** [comment]
Fixed. Will be out in the next release. For now it is still possible to scroll using the scroll wheel.
