### ISSUE TITLE
[Feature] Code autoscroll while executing.

### ISSUE THREAD

**Issue by Houkime** [MarvellousSoft/MarvInc#185]
Would be nice if codescreen could automatically keep active command row inbound while executing instead of letting it get away from screen.

To avoid too much movement logic could be to take a scrolling action only when an active row pushes against the edge/jumps out of bounds.

**Comment by rilifon** [comment]
Both this issue and #184 should be easy to implement. @yancouto will be better suited for this issue.

**Comment by yancouto** [comment]
I was going to implement this, but I think it will look bad when you have a bunch of code running fast (like in some late puzzles), then it will keep scrolling like crazy. So I won't fix this for now.
