### ISSUE TITLE
Enhancement: Allow login by clicking on the username

### ISSUE THREAD

**Issue by Ingix** [MarvellousSoft/MarvInc#194]
From a usuability perspective it seems a bit stange that the 'once in a lifetime' action of deleting your fictional account is easily reachable from the login screen, while simply allowing to click on the  login name(s) displayed there to move that name into the login form when the user wants to start the game (something the user has to do very often) is not possible.

So I suggest (as a slight improvement, if possible) to implement that.

**Comment by rilifon** [comment]
Closed, also adding some hover effects to menu buttons
