### ISSUE TITLE
Feature request: leave state visible on fail

### ISSUE THREAD

**Issue by mathuin** [MarvellousSoft/MarvInc#202]
Right now when I make a mistake, I get a modal dialog describing the failure, and the registers are zeroed and the line indicator is removed.

It would be very nice for the user to see the state of the system as the failure occurred.  Leave the registers and line indicator so we can see our mistake, instead of having to step until we find the failure again. :-)

**Comment by yancouto** [comment]
Very reasonable request, we'll look into it.
