### ISSUE TITLE
Bot talk option resets sometimes

### ISSUE THREAD

**Issue by pgimeno** [MarvellousSoft/MarvInc#207]
Sometimes, with the bot talk option disabled in preferences, the bot still talks. I am not sure, but I think it happens whenever a bot is replaced.

A workaround is to re-enable and re-disable it every time it happens.
Edit: Actually that workaround doesn't help. The one that helps is to hit "reply" in the email again.

**Comment by rilifon** [comment]
Lets just add another seettings option. One for "Remove regular bot messages", other for "Remove introductory bot messages"

**Comment by pgimeno** [comment]
If it was just these introductory messages it would be OK, but actually the bot continues with more messages after a while. I wouldn't need such an option, I just want them to at least stay quiet after they have introduced themselves, when I have disabled bot messages.

Try this patch to see it more quickly:

```diff
diff --git a/marv/classes/room.lua b/marv/classes/room.lua
index b39db22..0fe4a98 100644
--- a/marv/classes/room.lua
+++ b/marv/classes/room.lua
@@ -13,7 +13,7 @@ local Reader = require "classes.reader"
 
 --LOCAL VARIABLES--
 
-local max_time_between_bot_messages = 200
+local max_time_between_bot_messages = 3
 local min_time_between_bot_messages = 2
 local bot_message_timer_handle = nil
```

**Comment by pgimeno** [comment]
There seems to be something else broken. It seems the setting isn't saved or restored properly.

On reflection, the setting's name is "Robot Messages Popup" - I wouldn't expect any messages from bots at all if that is disabled. If that setting is supposed to only affect some messages, maybe it could be renamed to "Extra Robot Messages".

**Comment by oprypin** [comment]
I think this setting is just forgotten when the game restarts

**Comment by yancouto** [comment]
I'll look into that. Thank you for the report.
(By the way, this setting is supposed to be stored for each user, so if you open a new user it will "reset" for that user, but it seems the problem is bigger than that).

**Comment by RenatoGeh** [comment]
All settings are (seemingly) being properly stored and retrieved on login. The problem is the settings page is reading values before they are set by `save_manager`, so they are shown as their defaults instead. This might be only part of the problem, though. We'll investigate this issue further.

**Comment by yancouto** [comment]
The problem was the intro message was sent multiple times. I fixed that. I also added an option to disable the intro messages.
