### ISSUE TITLE
Leaderboard and statistics

### ISSUE THREAD

**Issue by RenatoGeh** [MarvellousSoft/MarvInc#212]
On ticks, lines of code, etc.

**Comment by yancouto** [comment]
- [ ] Show chart somewhere else that's not the puzzle complete screen (on the puzzle tab?)
- [ ] Show friends on chart
- [ ] Decide if we show your current or best score (or both?)
- [ ] Store ticks (complicated, will need its own issue when the time comes)
- [ ] (Undecided) Store number of used registers (after everything works for ticks, this should be pretty easy)

**Comment by yancouto** [comment]
This is working :)
In the end, we decided to use simply "Lines" and "Cycles"
