### ISSUE TITLE
Clothing drawn over hair

### ISSUE THREAD

**Issue by yancouto** [MarvellousSoft/MarvInc#215]
I was playing and once the clothes were drawn over the long hair. When the bot turned right this was fixed, so maybe this means "undefined drawing order", or maybe I'm just crazy.

**Comment by rilifon** [comment]
I think you are crazy hahah just checked drawing order and the hair is drawn after head and body. Maybe it was jsut optical illusion? It happened a bit to me when the hair color was very similar to body color. I'll close this issue until the bug shows again
