### ISSUE TITLE
Add an icon for our game when running in taskbar

### ISSUE THREAD

**Issue by rilifon** [MarvellousSoft/MarvInc#219]
The amoeba icon is just for the mini-icon on top of the game window. The icon displayed on the taskbar is still LOVE's.

**Comment by yancouto** [comment]
https://love2d.org/wiki/love.window.setIcon

**Comment by rilifon** [comment]
Love's set icon only sets the window Icon. The task bar icon depends on how we are building the game. Changed the name of the issue to reflect what was actually solved
