### ISSUE TITLE
Inconsistent naming for AppImage

### ISSUE THREAD

**Issue by RenatoGeh** [MarvellousSoft/MarvInc#232]
https://github.com/MarvellousSoft/MarvInc/blob/9d61eb816f213685aee303cba062c65a1f3eef55/deploy.sh#L101

Fix ASAP.

**Comment by rilifon** [comment]
Actually, I changed our launch options to this one "Marvellous_Inc-x86_64.AppImage", so I guess we just stick to this one and everything should be fine

**Comment by rilifon** [comment]
Closing this, for reasons stated above

**Comment by RenatoGeh** [comment]
This issue is not resolved. There are other parts in the code that should be fixed to comply with the current naming.
