### ISSUE TITLE
Steam workshop integration

### ISSUE THREAD

**Issue by rilifon** [MarvellousSoft/MarvInc#233]
Integrate our game with steamworkshop so that people can use that interface to send their own puzzles!

**Comment by rilifon** [comment]
https://github.com/SeStudio/steamworks-lua-integration

This will be useful. Although the example given just crashes on my PC kkk

**Comment by rilifon** [comment]
Sent email to SeStudio for help in using his libraries for other OS. Waiting his reply

**Comment by rilifon** [comment]
They replied saying its not compatible with other OSs. I've sent an email to another indie dev company that has a LOVE2D game on steam, runs on all OSs and has achievements, in hopes they can help.

@RenatoGeh says he  will try to help building a love binary with steamworks library using our script

**Comment by yancouto** [comment]
For reference, we're now using https://github.com/uspgamedev/luasteam for steam integration.

Workshop support is working (there are just some missing features in the custom level API, like lasers)
