### ISSUE TITLE
Custom Level

### ISSUE THREAD

**Issue by dulsi** [MarvellousSoft/MarvInc#265]
I created a custom level. When I run it on the steam version it fails. I get an error:

classes/puzzle.lua:81: attempt to call field 'custom_completed' (a nil value)

Am I doing something wrong?

http://identicalsoftware.com/dulsi/bitfield.lua

**Comment by dulsi** [comment]
Found the problem I think. Custom levels will always generate that error in 1.3.3. Dev has this:

elseif self.custom_completed then
                self.custom_completed()
            end

self.custom_completed is nil so it is never called. 1.3.3 just calls self.custom_completed() which is nil.

**Comment by RenatoGeh** [comment]
Hi dulsi,

You've nailed the problem. That is a known issue in the current stable builds.

We were initially planning on releasing a working custom level script and parser together with leaderboards. But life got in the way, and we ended up not picking MarvInc up again. You've somewhat given us some incentive to finally work on this next patch, but we can't promise you anything. :) We just need to make level scripting 100% safe for the end-user, but it's mostly complete.

Thanks,
Renato

**Comment by dulsi** [comment]
You need incentive? How about a level built using the new API?

[bitfield.zip](https://github.com/MarvellousSoft/MarvInc/files/3953630/bitfield.zip)

Seems completing the level doesn't mark the email as complete.

**Comment by RenatoGeh** [comment]
Hi dulsi,

You'll be happy to know that we've released a new version (dubbed Quarantined Edition) of MarvInc with the necessary changes for custom level creation and sharing through Steam Workshop. You can read more about it on the [Releases](https://github.com/MarvellousSoft/MarvInc/releases/tag/v1.4.0) page or [Steam](https://store.steampowered.com/app/827940/Marvellous_Inc/) page.

I'm closing this issue.

Hidrate yourself and stay safe,
Renato
