### ISSUE TITLE
Cannot run code on the reverse sequences level

### ISSUE THREAD

**Issue by lyiriyah** [MarvellousSoft/MarvInc#267]
I am on Manjaro Linux and installed from the AUR. When I click any of the play buttons it makes a noise and doesn't do anything.

**Comment by RenatoGeh** [comment]
I'll look into it. The AUR package is out of date.

**Comment by RenatoGeh** [comment]
The package has been updated. Please let me know if the error persists.

**Comment by lyiriyah** [comment]
@RenatoGeh sorry for late reply, i still can't run code

**Comment by lyiriyah** [comment]
i'll try and build from git

**Comment by RenatoGeh** [comment]
The AUR package builds from git already. Which level exactly is giving you this error? And what's the error output?

**Comment by lyiriyah** [comment]
There is no error output but it is the level where you read sequences from a terminal and reverse them
