### ISSUE TITLE
Create Sewer tiles

### ISSUE THREAD

**Issue by rilifon** [MarvellousSoft/MarvInc#36]
Create Sewer themed tiles to use in sewer themed puzzles

**Comment by rilifon** [comment]
Is there a level that can be sewer themed? If not, I won't bother doing this.

Thoughts? @yancouto @RenatoGeh

**Comment by yancouto** [comment]
No. I think you should focus on doing office props and more heads/bodies/props.

**Comment by rilifon** [comment]
someone please create an issue with a prop list so I can have some guidelines then. I think we already have an issue for more heads and bodies.

Will close this issue since it is no longer relevant
