### ISSUE TITLE
Change all dashes to underscores

### ISSUE THREAD

**Issue by yancouto** [MarvellousSoft/MarvInc#39]
It is not consistent right now

**Comment by rilifon** [comment]
Ctrl+Shift+F and a free afternoon should do the trick haha

**Comment by RenatoGeh** [comment]
`:args **/*.lua | bufdo %s/\<\w\+\>-\<\w\+\>/\1_\2/gc`

Should work on vim.

**Comment by RenatoGeh** [comment]
`bufdo %s/\(\<\w\+\>\)-\(\<\w\+\>\)/\1_\2/gc` is the correct command.
