### ISSUE TITLE
Laser rays can be blocked by dropables (buckets, etc.)

### ISSUE THREAD

**Issue by yancouto** [MarvellousSoft/MarvInc#45]
The laser can be "dinamically" altered when the surface is. For example if a new wall appears the laser will "contract".

One possible idea is to create the lases every turn, depending on the current environment. This would be ideal I think, and not too hard to implement.

**Comment by rilifon** [comment]
Isn't this done since the bodies on jen7 block the lasers? 
@yancouto @RenatoGeh is this a closed issue?

**Comment by yancouto** [comment]
Yes, just implemented this.
