### ISSUE TITLE
Window icon

### ISSUE THREAD

**Issue by yancouto** [MarvellousSoft/MarvInc#50]
Currently the game has no icon, it defaults to love's one.

**Comment by rilifon** [comment]
I can make one as soon as I'm back. Was thinking a black-n-green 'Mi' or just 'M',  or an amoeba. Other suggestions?

**Comment by yancouto** [comment]
I like the amoeba. In fact, let me test this
![amoeba](https://avatars0.githubusercontent.com/u/24594455?v=3&s=200)
