### ISSUE TITLE
Grid numbering improvement

### ISSUE THREAD

**Issue by yancouto** [MarvellousSoft/MarvInc#53]
The lineWidth is not being set (it just uses the one currently set, and may change during the game)

Maybe the color of the lines and numbers should be darker, maybe with some alpha, because they are very flashy this way.

Also, it should not appear when a room is not loaded.

**Comment by rilifon** [comment]
Maybe add some juicy effect where the alpha keeps transitioning between x and 255? It would look like the numbers are flashing

**Comment by yancouto** [comment]
It could look good.

**Comment by RenatoGeh** [comment]
This could also look quite distracting to the user. A possibility would be, when the bot is at (x, y), both x and y flash.

**Comment by yancouto** [comment]
This is nice! Flash or change color or something else, as long as it is emphasized.
