### ISSUE TITLE
Rename puzzle id's

### ISSUE THREAD

**Issue by yancouto** [MarvellousSoft/MarvInc#54]
We should rename puzzle id's because they are the name of the files that will be saved.

Suggestion 1: Name of the level, but in lowercase and with underlines instead of spaces
Suggestion 2: partnumber, like the lore_events (for example tuto1, jen2, ...)

@RenatoGeh what do you suggest?

**Comment by rilifon** [comment]
I liked the second suggestions best, since its better to visualize where the puzzle fits in the lore

**Comment by yancouto** [comment]
Sure, will do.

**Comment by RenatoGeh** [comment]
2
