### ISSUE TITLE
Add spam mail

### ISSUE THREAD

**Issue by yancouto** [MarvellousSoft/MarvInc#74]
Maybe one with a reply function that fucks things up :P

**Comment by RenatoGeh** [comment]
A subsequent email chain could trigger if you press reply. Once you press reply you get a virus on your computer. The MarvInc IT guy would then ask what were you thinking and to report the issue via a ticket. Replying this email would work as issuing a ticket on IT. After a few seconds everything goes back to normal and you get another email from the same IT guy warning you to never do that again and that the virus has been removed.

**Comment by rilifon** [comment]
we should do this and reward an achievement. Whenever we get the time to actually implement those

**Comment by yancouto** [comment]
This is done. There is a spam email in each Act.
