### ISSUE TITLE
Email for promotion

### ISSUE THREAD

**Issue by yancouto** [MarvellousSoft/MarvInc#96]
Email from Jen telling you got a promotion (after puzzle Jen3), you got Fergus position. Tells you to not worry about him, you will not see him around anymore. Things will be a lot more challenging from now on.

Pop up will appear congratulating you, and after clicking ok, change to "downloading new os" screen between acts. (Depends on #97 )

**Comment by yancouto** [comment]
#97 is done. Now the "trigger" has to be moved from the puzzle popup to this email.

**Comment by rilifon** [comment]
Made email. Need to change the trigger properly. @yancouto can you do it?
