### ISSUE TITLE
Diego emails for Act 2

### ISSUE THREAD

**Issue by yancouto** [MarvellousSoft/MarvInc#98]
- [x] DM: Diego is happy you got the job, but worried he almost got fired
- [x] DM: Diego says Paul sent him a task from Finance, and he sees some weird medical costs.
- [x] D1: Suspicious, says people are sending more tasks since he started asking questions (puzzle chess)
- [x] DM: Diego says he was walking in the cafeteria when he heard talk about a truck of 'medical waste' that was supposed to leave.
- [x] D2: #100 (lasers)
- [x] DM: THEY USE PEOPLE

**Comment by rilifon** [comment]
Created email and lore event files for everything. Still need to write the content of emails and set the dependencies
